### ISSUE TITLE
saving a model looses RE variance 

### ISSUE THREAD

**Issue by mebrooks** [glmmTMB/glmmTMB#177]
Here is an example.
```
data(sleepstudy, package="lme4")
fm1 <- glmmTMB(Reaction ~ Days +     (1|Subject), sleepstudy)
summary(fm1)
save(fm1, file="fm1.Rdata")
load("fm1.Rdata")
summary(fm1)
```
The original model has 1294.3 variance for the random effect of subject. After saving the model and reloading it, the variance is 1.

**Comment by kaskr** [comment]
It is essentially fixed by ecaffa1d8680a60f0e9edc8eb5455119fd18a81b. However, a few travis tests are affected:

```
  Running ‘AAAtest-all.R’ [64s/64s]

 ERROR

Running the tests in ‘tests/AAAtest-all.R’ failed.

Last 13 lines of output:

  Error: `c1` not equal to c(...).

  1/6 mismatches

  x[5]: "          age         0.21492  -0.581"

  y[5]: "          age         0.21492  -0.582"

  testthat results ================================================================

  OK: 93 SKIPPED: 0 FAILED: 4

  1. Failure: beta (@test-families.R#31) 

  2. Failure: nbinom (@test-families.R#47) 

  3. Failure: nbinom (@test-families.R#62) 

  4. Failure: dbetabinom (@test-families.R#82) 

  ```

**Comment by bbolker** [comment]
haven't checked yet, but presumably (???) this is just a matter of adding some tolerances to `expect_equal` tests ... (if not, this seems scary)

**Comment by mebrooks** [comment]
I checked here
https://travis-ci.org/glmmTMB/glmmTMB/builds/166662204
and it looks like it's a small difference in one of the tests, but I'm not very experienced with checking travis output. Should we merge the fix into the master?
```
Running the tests in ‘tests/AAAtest-all.R’ failed.
Last 13 lines of output:
  Error: `c1` not equal to c(...).
  1/6 mismatches
  x[5]: "          age         0.21492  -0.581"
  y[5]: "          age         0.21492  -0.582"
```

**Comment by kaskr** [comment]
The old version is buggy. It uses the `last.par` for the `report` function which is randomly different from the optimal parameter.
So, the branch should definitely be merged... But the expected output must be changed as well (the tolerances should remain unchanged).

**Comment by mebrooks** [comment]
I tried making the same change as in the fix_varcorr branch to my own version, and I'm still getting the same problem with the example above. @kaskr did you test it? I tried updating TMB also.

**Comment by kaskr** [comment]
Yes, I did test it... Will try again later.

**Comment by kaskr** [comment]
Sorry, you are right @mebrooks - my fix does not work.

The problem in this thread is part of a broader issue. When using the TMB function `report` one must be careful not to rely on the internal state of the TMB object (saving/loading as well as likelihood profiling could leave the object in an unexpected state...). Currently I see (on the master branch):

```shell
grep '$report' *.R
predict.R:      return(newObj$report(lp)$mu_predict)
VarCorr.R:    xrep <- x$obj$env$report()
```

The `predict` function does it right by updating the internal structures before reporting. We could adopt that for `VarCorr` as well. However, rather than running updates for each case, it would be cleaner (and faster) to store the full parameter vector `lp` as part of `object$fit` after calling `nlminb` optimization. I will work out a new fix later.
