### ISSUE TITLE
deviance value from glmmTMB object

### ISSUE THREAD

**Issue by jsanket123** [glmmTMB/glmmTMB#621]
In glmmTMB.R file on line 1149 
deviance = -2*llik 
should be changed to 
deviance = c(-2*llik)

Otherwise stats::deviance(x) always returns NULL

I checked stats::logLik(x) which returns some numerical value (for snaity check) since on line 1148
logLik = c(llik)
is assigned like this and it works fine.

Also is there a way to change the source code locally on R for me to fix the bug in my locally installed glmmTMB package?

**Comment by bbolker** [comment]
The easiest way for you to fix the bug is to download the package code from GitHub, change the source code, and re-install from your local copy.  But it's also likely that we can fix this pretty quickly, if your diagnosis checks out.

**Comment by bbolker** [comment]
I'm a little confused, I don't see how this fixes the problem. Can you give a reproducible example?

My diagnosis of the problem is that (1) `glmmTMB` objects are missing a `deviance()` method; (2) the default `stats::deviance` assumes that the deviance is stored as a `$deviance` element in the object (which it's not).

It would be very easy to add

```
deviance.glmmTMB <- function(object, ...) {
   -2*c(logLik(object))
}
```

In fact, you can add this function to your global environment, and it should solve the problem locally (even without modifying the package). **HOWEVER**: there are some fairly deep issues relating to the definition of 'deviance' for GLMMS: see [here](https://github.com/lme4/lme4/blob/master/man/merMod-class.Rd#L201-L224).  We should consider these issues at least briefly before committing to an implementation of `deviance.glmmTMB` ...

**Comment by jsanket123** [comment]
I am not completely aware of the issues related to the deviance of GLMM. I was using check_heteroscedasticity function from the performance package and it was giving an error. Then I went to the code of that function and I saw the problem was with stats::deviance(model object) which when I ran locally gave me NULL value with glmmTMB model. 

I am currently facing issues in installing glmmTMB from my local zip file. Once I resolve it I will check what I get with what I suggested as well as you suggested.

**Comment by bbolker** [comment]
OK.  Another possibility if you're comfortable with GitHub is to fork this repository, clone it locally, make the changes you want, push them back to GitHub, then `remotes::install_github()` from your fork.

**Comment by jsanket123** [comment]
Hello Ben,

I tried my suggestion and you were right that it didn't solve the problem. I used your suggestion of creating a global environment function for deviance calculation in glmmTMB and it worked fine. although now from our discussion I am little bit concerned about using check_heteroscedasticity function with this deviance since you said that deviance in GLMM models have serious issues.

**Comment by bbolker** [comment]
I'm glad it worked. I think "serious issues" may be an overstatement.  You should be OK *as long as you are comparing a single set of models within a single platform*.  The possibilities for making a mistake may arise if:

* you compare across platforms, e.g. `glmmTMB` vs `glm` (this isn't as big a deal as with `lme4` because, unlike `lme4`, `glmmTMB` can fit models without random effects
* you are relying heavily on the theoretical properties of deviance as defined in the GLM literature (where it is almost always defined as the *relative* deviance, i.e. `-2*(L-L_saturated)`)

If you are working with continuous response distributions many of the problems go away, as the saturated model for continuous-response distributions typically has a likelihood of 1 (and hence a log-likelihood of 0).

**Comment by jsanket123** [comment]
Thank you for all of your help with this issue. Also, I had a question regarding the covariance structures using glmmTMB (https://cran.r-project.org/web/packages/glmmTMB/vignettes/covstruct.html). I was hoping I could directly email you about it or should I ask here?

**Comment by bbolker** [comment]
See https://github.com/glmmTMB/glmmTMB#where-to-ask-questions and use your judgment (hint: direct e-mail is the *last* choice :-) )
